-- ? 1. Script Oracle 19c:
-- Tabla
CREATE TABLE CLIENTES_F (
    ID            NUMBER PRIMARY KEY,
    CONSECUTIVO   NUMBER,
    NOMBRE        VARCHAR2(100),
    EMAIL         VARCHAR2(100),
    TELEFONO      VARCHAR2(50)
);

-- Secuencia
CREATE SEQUENCE SEQ_CLIENTES START WITH 1 INCREMENT BY 1;

-- Trigger autoincremental
CREATE OR REPLACE TRIGGER TRG_CLIENTES
BEFORE INSERT ON CLIENTES_F
FOR EACH ROW
BEGIN
    SELECT SEQ_CLIENTES.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/

COMMIT;